[package]
name = "rust_tools"
version = "0.1.0"
authors = ["sxend <arimitsu.k+github@gmail.com>"]

[dependencies]
time = "0.1.38"
uuid = { version = "0.5.1", features = ["v1", "v4"] }
docopt = "0.8.1"
serde = "1.0.10"
serde_derive = "1.0.10"
url = "1.5.1"
percent-encoding = "1.0.0"
